FROM python:3.11-slim

WORKDIR /app
COPY ./src/A-Financial-Knowledge-Graph-Construction-from-SET50-Annual-Reports-scoretest /app

RUN pip install --no-cache-dir -r requirements.txt

CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
