FROM python:3.10-slim

WORKDIR /app

# Copy shared requirements
COPY ./src/chatbot/requirements.txt /app/requirements.txt

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

COPY ./src/chatbot/thai /app

CMD ["streamlit", "run", "bot.py", "--server.port=8502", "--server.address=0.0.0.0"]
